version: 2.1

references:
  workspace_root: &workspace_root /go/src/github.com/jlesquembre/kubepromt
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root
executors:
  ci-executor:
    docker:
      - image: hairyhenderson/gomplate-ci-build:latest
    environment:
      CIRCLE_TEST_REPORTS: /tmp/test-results
    working_directory: *workspace_root

jobs:
  build:
    executor: ci-executor
    steps:
      - checkout
      - run: make build
      - store_artifacts:
          path: bin
          destination: artifacts
      - persist_to_workspace:
          root: *workspace_root
          # Must be relative path from root
          paths:
            - ./

  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(cat ./artifacts/VERSION)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
